import 'dotenv/config';

const {
    PRODUCT_CATALOGUE_NODE_ENV,
    PRODUCT_CATALOGUE_PORT,
    PRODUCT_CATALOGUE_DEV_URL
} = process.env

export default {
    PRODUCT_CATALOGUE_NODE_ENV,
    PRODUCT_CATALOGUE_PORT,
    PRODUCT_CATALOGUE_URL: PRODUCT_CATALOGUE_DEV_URL
}