import 'dotenv/config';

const {
    PRODUCT_CATALOGUE_NODE_ENV,
    PRODUCT_CATALOGUE_PORT,
    PRODUCT_CATALOGUE_PROD_DATABASE_URL,
    PRODUCT_CATALOGUE_PROD_BCRYPT_SALT_ROUNDS
} = process.env

export default {
    PRODUCT_CATALOGUE_NODE_ENV,
    PRODUCT_CATALOGUE_PORT,
    PRODUCT_CATALOGUE_URL: PRODUCT_CATALOGUE_PROD_DATABASE_URL,
    PRODUCT_CATALOGUE_BCRYPT_SALT_ROUNDS: PRODUCT_CATALOGUE_PROD_BCRYPT_SALT_ROUNDS
}