import 'dotenv/config';

const {
    PRODUCT_CATALOGUE_NODE_ENV,
    PRODUCT_CATALOGUE_PORT,
    PRODUCT_CATALOGUE_TEST_DATABASE_URL,
    PRODUCT_CATALOGUE_TEST_BCRYPT_SALT_ROUNDS,
    PRODUCT_CATALOGUE_TEST_JWT_SECRET_KEY,
    PRODUCT_CATALOGUE_TEST_SENDGRID_API_KEY
} = process.env

export default {
    PRODUCT_CATALOGUE_NODE_ENV,
    PRODUCT_CATALOGUE_PORT,
    PRODUCT_CATALOGUE_URL: PRODUCT_CATALOGUE_TEST_DATABASE_URL,
    PRODUCT_CATALOGUE_BCRYPT_SALT_ROUNDS: PRODUCT_CATALOGUE_TEST_BCRYPT_SALT_ROUNDS,
    PRODUCT_CATALOGUE_JWT_SECRET_KEY: PRODUCT_CATALOGUE_TEST_JWT_SECRET_KEY,
    PRODUCT_CATALOGUE_SENDGRID_API_KEY: PRODUCT_CATALOGUE_TEST_SENDGRID_API_KEY

}